### ISSUE TITLE
Double quotation should be removed.

### ISSUE THREAD

**Issue by rabiul0420** [magepeopleteam/bus-ticket-booking-with-seat-reservation#110]
![Screenshot_32](https://github.com/magepeopleteam/bus-ticket-booking-with-seat-reservation/assets/30313066/56c0ad87-61ec-443d-9001-4f36ca5ae57b)

**Comment by shohan777** [comment]
Colon comes from bus string setting

**Comment by rabiul0420** [comment]
Okay, Thanks.
